// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_repo.sql

package reposdb

import (
	"context"
)

const getRepo = `-- name: GetRepo :one
SELECT id, display_name, owner, name, path, remote, created_at, updated_at
FROM repos
WHERE id = $1
`

func (q *Queries) GetRepo(ctx context.Context, id string) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Owner,
		&i.Name,
		&i.Path,
		&i.Remote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
