// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_repo.sql

package reposdb

import (
	"context"
)

const insertRepo = `-- name: InsertRepo :one
INSERT INTO repos (id, display_name, owner, name, path, remote)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, display_name, owner, name, path, remote, created_at, updated_at
`

type InsertRepoParams struct {
	ID          string
	DisplayName string
	Owner       string
	Name        string
	Path        string
	Remote      string
}

func (q *Queries) InsertRepo(ctx context.Context, arg InsertRepoParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, insertRepo,
		arg.ID,
		arg.DisplayName,
		arg.Owner,
		arg.Name,
		arg.Path,
		arg.Remote,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Owner,
		&i.Name,
		&i.Path,
		&i.Remote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
