// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_repos.sql

package reposdb

import (
	"context"
)

const listRepos = `-- name: ListRepos :many
SELECT id, display_name, owner, name, path, remote, created_at, updated_at
FROM repos
ORDER BY id
`

func (q *Queries) ListRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Owner,
			&i.Name,
			&i.Path,
			&i.Remote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
