// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reposdb

import (
	"time"
)

type Repo struct {
	ID          string
	DisplayName string
	Owner       string
	Name        string
	Path        string
	Remote      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	AddedBy     string
}
